### ISSUE TITLE
Apache's Image in the Footer

### ISSUE THREAD

**Issue by Santeee** [groovy/groovy-website#102]
In the div with class='col-right' the Apache's Image is without the class='img-responsive'.

`<img src="img/xasf_logo.png.pagespeed.ic.oYGxdP6oSc.png" title="The Apache Software Foundation" alt="The Apache Software Foundation" class="img-responsive">`

**Comment by glaforge** [comment]
Do you want to provide a pull request with the change?

**Comment by Santeee** [comment]
Yeah!
It's mi first contribution, i did it well?

**Comment by glaforge** [comment]
Thanks for your contribution :-)
Let's see what it looks like once the CI server will have rebuilt and redeployed the website.

**Comment by Santeee** [comment]
Your welcome!
Is a very little change, i expect to contribute more. 

Regards
