### ISSUE TITLE
Documentation improvements -- how to run groovy

### ISSUE THREAD

**Issue by jric** [groovy/groovy-website#116]
I tried to make these changes to the doc and submit a PR, but it was taking me too long to figure out the templating system, since I'm still new to groovy.  I would still like to offer my ideas for improving the documentation, in hopes that someone familiar with the build system can easily make the changes.

Proposals:
* on the [install page](http://groovy-lang.org/install.html), create a new section (6) entitled "Verify installation".  Move some of the content from section (5) to section (6).  The bit starting with "You should now have Groovy installed properly. You can test this by..." and ending with the command to test it.  I would probably simplify at this point and suggest using command `groovy -version` to verify proper installation.
* on the [documentation page](http://groovy-lang.org/documentation.html), add a new item after "Install Groovy" entitled "Run Groovy"
* move to the new "Run Groovy" page all the bits from section (5) of the install page, starting with "a command shell..."
* append to the new "Run Groovy" page all the info from [Groovy Shell Scripting](http://www.coderhut.com/2010/02/groovy-shell-scripting.html).  Three options for this:
** provide a link to the original posting
** get permission in writing from the original author to reproduce the content; in this case you'd probably want to add a tagline, "reproduced with permission from XXXXX" and check in the written permission to the codebase, not visible on the website, but so that it doesn't get lost
** rewrite the content from scratch

**Comment by paulk-asert** [comment]
Please reopen at apache/groovy-website if you think the proposals still make sense after the intervening time.
