### ISSUE TITLE
http://groovy-lang.org/closures.html Incorrect definition of "isOdd" closure

### ISSUE THREAD

**Issue by Exlll** [groovy/groovy-website#123]
`def isOdd = { int i-> i%2 == 1 }`

The % operation is defined as `(a/b)*b+(a%b) == a` with `(a/b)` rounding towards zero. That means the closure yields incorrect results for negative odd numbers.

Fix: `def isOdd = { int i-> i%2 != 0 }`

**Comment by paulk-asert** [comment]
Thanks for spotting that - fixed.
