### ISSUE TITLE
It looks frozen, can not finish.

### ISSUE THREAD

**Issue by jhzao82** [groovy/groovy-website#143]
It stop here for a long time, I have to kill it, any solustion?

```
Generating website using Groovy 2.4.15
Cache directory: build/cache
<==========---> 78% EXECUTING
> :site-user:generateSite
```

**Comment by paulk-asert** [comment]
Are you getting any further output? Does using --info help?

**Comment by paulk-asert** [comment]
I think this might have been an issue with the Jira instance. It seemed to be running extremely slowly a little while back. Can you try again - but also notice the the repo has moved:
https://github.com/apache/groovy-website/
