### ISSUE TITLE
My firefox can't see your google search bar

### ISSUE THREAD

**Issue by darachm** [groovy/groovy-website#146]
I can't see the google site search bar on (http://groovy-lang.org/search.html) when using Firefox 64.0 on Ubuntu.

It says:
`Loading failed for the <script> with source “http://www.google.com/cse/cse.js?cx=013939896723962546743:hbhn__olhii”`

This isn't an issue particular to your website, as I can see the google site search bar in Chromium. This is probably because I have the "block trackers" option on (that also blocks all Google Captcha). However, I thought it might be an accessibility concern if you want to make sure your site functionality doesn't rely on a third-party tracking your users through your website. Just in case you're concerned about that.

**Comment by paulk-asert** [comment]
Please reopen at apache/groovy-website if still a problem.
