### ISSUE TITLE
Integration with Groovyblogs.org

### ISSUE THREAD

**Issue by loboweissmann** [groovy/groovy-website#33]
Groovyblogs.org is the best blog aggregator we have for Groovy developers.
On the community section whould be really nice to see the content of that site on it. It's also a nice incentive for new Groovy bloggers to see their posts on the official Groovy website

**Comment by sbglasius** [comment]
being the developer of GroovyBlogs we could try and fine-tune the selection algorithm. Right now the blog that causes the most false-groovy-positives is http://groovy.dzone.com/ An analysis to why could probably fix that.

**Comment by paulk-asert** [comment]
I'll close this for now. There has been some thoughts about reworking groovyblogs.org. We can reopen at apache/groovy-website if that comes to fruition.
