### ISSUE TITLE
Site does not support all device screen widths

### ISSUE THREAD

**Issue by kastork** [groovy/groovy-website#42]
As with most sites employing fixed-width responsive designs, the new groovy site isn't friendly to all devices.  For example, on an iPad mini retina in portrait orientation, the site is rendered too wide for the device rather than flowing text to the browser's actual width.  Consequently, the reader is constantly having to move the page from left to right and back again just to finish reading a sentence.

This would not be a problem if normal pinch-zooming, or double-tap zooming worked, but they don't.

**Comment by paulk-asert** [comment]
Please reopen at apache/groovy-website if still a problem.
