### ISSUE TITLE
Some page resources in the beta domain don't load but work in docs domain

### ISSUE THREAD

**Issue by smartdreamer** [groovy/groovy-website#46]
Every page under http://beta.groovy-lang.org/docs/ does not load resources (images, JS, etc.). For example: http://beta.groovy-lang.org/docs/latest/html/documentation/markup-template-engine.html does not work.

The resources are requested at wrong URLs. An image like http://beta.groovy-lang.org/docs/latest/html/documentation/img/pivotal.png is in fact located at http://beta.groovy-lang.org/img/pivotal.png.

I've tried http://docs.groovy-lang.org/docs/latest/html/documentation/markup-template-engine.html and **it works**.

Note that the failed linked I provided was taken from an external site.

**Comment by melix** [comment]
It is actually not the problem. It is more a missing 404 page. The docs should not be available on `beta` but on `docs` only.

**Comment by melix** [comment]
Fixed by 9844a3e
