### ISSUE TITLE
stylesheet property prevent printing documentation 

### ISSUE THREAD

**Issue by pbvahlst** [groovy/groovy-website#57]
You have the following property set in one of your stylesheets. I prevents printing the documentation eg. http://groovy-lang.org/style-guide.html. When the properties are removed all pages can be printed

```
html, body{
   height:100%;
   -webkit-overflow-scrolling:touch;
}
```

**Comment by paulk-asert** [comment]
Please reopen at apache/groovy-website if still a problem.
