### ISSUE TITLE
Error in Documentation > Interface

### ISSUE THREAD

**Issue by skiwi2** [groovy/groovy-website#63]
As seen in the image below there's an error here:

![groovydocerror](https://cloud.githubusercontent.com/assets/2961606/7656118/b1476a92-fb28-11e4-9ab7-45dc5de5c584.png)

It looks the code block is incorrect.

The error can be found on the following page: http://docs.groovy-lang.org/latest/html/documentation/#_interface

**Comment by PascalSchumacher** [comment]
Thanks for reporting!

This will be fixed with the next release:

http://docs.groovy-lang.org/next/html/documentation/#_interface

**Comment by paulk-asert** [comment]
Fixed.
