### ISSUE TITLE
Typo in Documentation > Optional Typing

### ISSUE THREAD

**Issue by skiwi2** [groovy/groovy-website#64]
As seen in the image below there is a typo here:

![groovydocerror2](https://cloud.githubusercontent.com/assets/2961606/7658679/5d8e9330-fb3c-11e4-93fd-b36b5c8d6cd7.png)

The typo can be found on the following page: http://docs.groovy-lang.org/latest/html/documentation/#_optional_typing

**Comment by PascalSchumacher** [comment]
Thanks for reporting!

This will be fixed with the next release:

http://docs.groovy-lang.org/next/html/documentation/#_optional_typing

**Comment by paulk-asert** [comment]
Fixed.
