### ISSUE TITLE
Where is the style guide's source?

### ISSUE THREAD

**Issue by anshbansal** [groovy/groovy-website#69]
I found a typo in http://www.groovy-lang.org/style-guide.html and wanted to send a pull request. I spent half hour but couldn't find where the source for that page is. 

"But sometimes, this doesn’t look to good when" => It should be "too good".

**Comment by anshbansal** [comment]
It would be nice if the button for editing on github is also added to this page. Else add an entry in README

**Comment by anshbansal** [comment]
"you may be surprise to see " => Should be surprised

**Comment by anshbansal** [comment]
"first the constructor is called, then the setters are called in turn" ->  "the setters are called in the sequence in which they are specified in the map"

The sequence might matter in some cases. I am commenting as I keep on reading else I'll forget.

**Comment by anshbansal** [comment]
"Last but not least, prefer using single quoted strings when you need string constants". It would be goof to add why this should be done. I think it is performance. Is there anything else?

**Comment by anshbansal** [comment]
`assert 'foo' =~ pattern`

It should be
`assert 'foo' ==~ pattern`

Running the first I got `java.util.regex.Matcher[pattern=fo* region=0,3 lastmatch=]`. Running the second I got `true`

**Comment by anshbansal** [comment]
`case { it > 3 }` should be `case { it > 3 }:`. Missing colon.

**Comment by anshbansal** [comment]
"If you don’t really care of the exception" => "care about the type of exception"

**Comment by anshbansal** [comment]
bump

**Comment by melix** [comment]
The docs are in https://github.com/apache/incubator-groovy/blob/master/src/spec/doc/style-guide.adoc

Regarding `assert 'foo' =~ pattern`, it is not really an error, because of Groovy truth.

**Comment by anshbansal** [comment]
@melix But wouldn't that be always true and hence beat the point of the assert?

**Comment by PascalSchumacher** [comment]
@anshbansal No, the groovy truth requires the matcher to have at least one match to be considered true:
`assert ('a' =~ /a/)`

If the matcher does not have a match it is considered false:

`assert !('a' =~ /b/)`

http://docs.groovy-lang.org/latest/html/documentation/#_matchers
