### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by anshbansal** [groovy/groovy-website#70]
On the [design patterns](http://groovy-lang.org/design-patterns.html) page the images are broken. The same 

On website broken
http://docs.groovy-lang.org/latest/html/documentation/assets/img/ChainOfResponsibilityClasses.gif

On github working
https://raw.githubusercontent.com/apache/incubator-groovy/master/src/spec/doc/assets/img/ChainOfResponsibilityClasses.gif

**Comment by PascalSchumacher** [comment]
Hi anshbansal,

thanks for reporting. :)

This should already be fixed with the next version (groovy 2.4.4):

http://docs.groovy-lang.org/next/html/documentation/assets/img/ChainOfResponsibilityClasses.gif

We just need to finally release this version.

**Comment by PascalSchumacher** [comment]
With the release of 2.4.4 the link works: http://docs.groovy-lang.org/latest/html/documentation/assets/img/ChainOfResponsibilityClasses.gif

Issue can be closed. Thanks!

**Comment by melix** [comment]
Thanks for the confirmation!
