### ISSUE TITLE
Broken links for Groovy truth

### ISSUE THREAD

**Issue by anshbansal** [groovy/groovy-website#71]
There are links for groovy truth on the URL http://www.groovy-lang.org/operators.html which are broken.
http://www.groovy-lang.org/operators.html#Groovy-Truth

**Comment by PascalSchumacher** [comment]
I guess this is a general problem. Links to different sections work in the single page documentation http://groovy-lang.org/single-page-documentation.html only.

**Comment by PascalSchumacher** [comment]
My last comment was wrong, it is possible to link to different sections in the multipage version.

I fixed the links in https://github.com/apache/incubator-groovy/commit/4475fa6dc806ee8ebdcb2e392e1d80a4b49f4faf

They will be fixed on the website with the next groovy release.

Thanks for reporting this. :+1:

**Comment by PascalSchumacher** [comment]
With the release of groovy 2.4.5 the links now work. Can somebody please close this issue? Thank!

**Comment by glaforge** [comment]
By the way @PascalSchumacher, I've added you to the committers group of this repository.

**Comment by PascalSchumacher** [comment]
@glaforge Thanks!
