### ISSUE TITLE
Image positions on home page

### ISSUE THREAD

**Issue by najawa** [groovy/groovy-website#89]
Hello,

I noticed a few display bugs with your home page. I'm viewing from OSX on a 2013 Macbook Pro 13" Retina (2560x1600 pixels, rendering at 1280 x 1024).

The Apache Foundation Logo at the bottom needs to have "float:right;" added to it's img element.

The Wells Fargo Logo in your 'Companies that use us' section looks bad at all sizes, and just needs to go.

Best of luck!

**Comment by PascalSchumacher** [comment]
Hi Nate,

thanks for reporting this.

I fixed the Wells Fargo Logo issue.

I'm not knowledgeable about the website is created/generated to figure out where I have to add the "float:right" to the Apache Logo.

Sorry. :(

**Comment by paulk-asert** [comment]
I'll close this for now. Please re-open against the new repo if this is still a problem:
https://github.com/apache/groovy-website/
