### ISSUE TITLE
Provide secure download method

### ISSUE THREAD

**Issue by pradtke** [groovy/groovy-website#90]
The download links (on http://groovy-lang.org/download.html) provided for binary, source, sdk bundle and windows installer are all http.  How am I suppose to know what I'm downloading hasn't been compromised in transit? Can they be https links or can you list the correct md5 hashes for the downloads?

Also the sdkman instruction are scary. It is asking me to download something of http and just run it. How do I know it hasn't been tampered in transit? is there a secure way of using sdkman?

**Comment by PascalSchumacher** [comment]
Hi Patrick,

I will update the links to use https.

About sdkman, a quick search did not yield a secure way to use it, but you can raise an issue at https://github.com/sdkman/sdkman-cli

Cheers,
Pascal
