### ISSUE TITLE
Typo in metaprogramming.html page

### ISSUE THREAD

**Issue by ivaylomarinovski** [groovy/groovy-website#91]
Hello,

There seems to be a typo in the  [metaprogramming page](http://www.groovy-lang.org/metaprogramming.html#_get_setmetaclass).

![typo](https://cloud.githubusercontent.com/assets/4374841/14398437/e7eda12a-fdec-11e5-9650-c264d13cfe9e.png)

In the sentence:

"You can a access a objects metaClass or set your own MetaClass implementation for changing the default interception mechanism."

probably the part: "You can a access a objects metaClass" should be replaced by: "You can access an object's metaClass".

Best regards,
Ivaylo

**Comment by PascalSchumacher** [comment]
Thanks for reporting. :)

Fixed in: https://github.com/apache/groovy/commit/fa790d1aadb78290b906c930d2bdeaa039dc33f0

Website will be update with the next groovy release.

Cheers,
Pascal

**Comment by ivaylomarinovski** [comment]
Hey, Pascal

Great to hear.

Thank you!

Best regards,
Ivaylo
