### ISSUE TITLE
Common events calendar

### ISSUE THREAD

**Issue by sbglasius** [groovy/groovy-website#93]
I suggest that a website to manage events is to be made, that way event makers and conference organizers has one central place to maintain conferences related to Groovy.

When I get around to it, I will start such initiative. This is a placeholder to see if there is any interest in the matter.

Also suggested for the Grails website: https://github.com/grails/grails-static-website/issues/43

**Comment by melix** [comment]
Cannot lanyrd be used for that purpose?

Le 30 juin 2016 11:52, "Søren Berg Glasius" <notifications@github.com> a
écrit :

**Comment by glaforge** [comment]
I don't think Lanyrd have an official API, do they?

**Comment by sbglasius** [comment]
I don't see an official API. Apparently there is an unofficial API https://github.com/andrew/lanyrd - but Ruby? ;)

**Comment by paulk-asert** [comment]
Please reopen at apache/groovy-website if still a problem.
