### ISSUE TITLE
Site Generator Errors

### ISSUE THREAD

**Issue by cfaddict** [groovy/groovy-website#94]
I just pulled down the site and before I even do anything If I open up 

/src/groovy/main/generator/SiteGenerator.groovy there are all kinds of errors going on here. Does anyone know what's happening here? 

![site_generator](https://cloud.githubusercontent.com/assets/349507/17175128/bd8d0d7a-53d3-11e6-9bb6-566eadfe362e.png)

**Comment by glaforge** [comment]
The IDE might be giving a bit too strict error messages at times, although the code is perfectly valid and functioning.

**Comment by cfaddict** [comment]
OK - I was just curious. Thank you!
