### ISSUE TITLE
"Fork me on Github" image placement occludes the scrollbar

### ISSUE THREAD

**Issue by jameyg42** [groovy/groovy-website#96]
The "Fork me on Github" image floats over the vertical scrollbar.  When scrolled to the top of the page, the image completely covers the scrollbar thumb making it impossible to click/drag scroll.  The linkable region is also the bounding box of the image (vs. the triangular slice)

i like visiting github...but i've done it unintentionally about a dozen times already today reading the Docs :)

![image](https://cloud.githubusercontent.com/assets/2145867/17221189/be05fe36-54c0-11e6-80cc-b49e12aa98d0.png)
clickable region in red, occluding scrollbar thumb(s)

**Comment by amdelamar** [comment]
**_// bump_**

This should be a good first issue, for any html/frontend developers to make a PR for.

**Comment by paulk-asert** [comment]
Fixed. See changes on the new repo:
https://github.com/apache/groovy-website/
