### ISSUE TITLE
anchor history is misbehaving

### ISSUE THREAD

**Issue by jameyg42** [groovy/groovy-website#97]
something appears to be interfering w/ the regular behavior of anchor history.  Clicking on an anchor link properly brings you to the anchor position
![image](https://cloud.githubusercontent.com/assets/2145867/17221361/8bcc9e74-54c1-11e6-87e1-1c42b9244531.png)

but clicking "back" from this point has no effect
![image](https://cloud.githubusercontent.com/assets/2145867/17221385/af97e70a-54c1-11e6-8387-d307b8bb12e2.png)

vs. the expected behavior of returning to the part of the document where the anchor link was clicked.  

this makes navigating the Documentation pages very difficult

**Comment by paulk-asert** [comment]
Please reopen at apache/groovy-website if still a problem.
