### ISSUE TITLE
Too many scrolls

### ISSUE THREAD

**Issue by leosilvadev** [groovy/groovy-website#98]
There is too many scrolls using from my notebook.

Linux Mint
Chrome Version 51.0.2704.84 (64-bit)

![groovy-website](https://cloud.githubusercontent.com/assets/5465808/17503538/03fe5d7a-5dc7-11e6-813d-3eae3fd2ed9f.png)

**Comment by wilson-jetbloom** [comment]
What is the suggestion? Make the logo smaller?

**Comment by leosilvadev** [comment]
Sorry for the delay.
Checked out here now and it does not happen anymore.
